/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./src/**/*.{html,js,ts,tsx}"],
  theme: {
    extend: {
      colors: {
        transparent: "transparent",
        current: "currentColor",
        white: "#ffffff",
        midnight: "#121063",
        metal: "#565584",
        tahiti: "#3ab7bf",
        silver: "#ecebff",
        "bubble-gum": "#ff77e9",
        bermuda: "#78dcca",
        accent: "#304FFD",
        orange: "#FF965D",
        red: "#FD7972",
        yellow: "#FFD240",
        blue: "#22CCE2",
        green: "#49C96D",
        darkGreen: "#20A144",
        darkOrange: "#E56E19",
        darkYellow: "#E6B823",
        darkRed: "#F05C54",
        darkBlue: "#009EB3",
        purple: "#B656EB",
        pink: "#F9DDC5",
        heading: "#3F434A",
        bodyLight: "#1A161F",
        bodyDark: "#595F69",
        grey: "#C6C9CC",
        borderColor: "#E8E9EB",
        BG: "#F8F8F8",
        bodyColor: "#0D0C0F",
      },
    },
  },
  plugins: [],
};
